version: '2'

services:

  # Web Server
  nginx-web:
    image: nginx:1.13.7
    expose:
    - '80'
    labels:
      io.rancher.container.pull_image: always
      
  # Load Balancer    
  loadbalancer:
    image: rancher/lb-service-haproxy:v0.7.15
    ports:
    - 443:443/tcp
    
    labels:
    
      # Rancher
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'
      io.rancher.scheduler.global: 'true'
      
      traefik.enable: 'true'
      traefik.protocol: 'https'
      traefik.alias: '${SUBDOMAIN}'
      traefik.domain: '${DOMAIN}'
      traefik.frontend.rule: '${SUBDOMAIN}.${DOMAIN}'
      traefik.port: '443'
      traefik.acme: 'false'
      traefik.path: '/'
