version: '2'

# Catalog
catalog:
  name: "Sample nginx"
  version: "v0.0.1"
  description: "A sample nginx server"

services:

  # Web Server
  nginx-web:
    scale: 2
    start_on_create: true
   
  # Load balancer
  loadbalancer:
    start_on_create: true
    
    lb_config:
    
      certs:
      - default
      
      default_cert: default
      
      port_rules:
      
      # HTTP traffic
      - priority: 1
        protocol: http
        service: nginx-web
        source_port: 80
        target_port: 80
      
      # HTTPS traffic  
      - priority: 2
        protocol: https
        service: nginx-web
        source_port: 443
        target_port: 443
        
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
