version: '2'

# Catalog
catalog:
  name: "Sample nginx"
  version: "v0.0.1"
  description: "A sample nginx server"
  
  # User questions
  questions:
  
  # Name of the certificate to use
  - variable: "EXTERNAL_FQDN"
    type: "string"
    label: "Full qualifier domain name"
    description: "The FQDN. Must match service FQDN in the following format : <stack_name>.<external DNS domain>. Example nginx-sample.dsu.nestle.biz"
    default: "nginx-sample.dsu.nestle.biz"
    required: true  
  
  # Name of the certificate to use
  - variable: "CERTIFICATE_NAME"
    type: "string"
    label: "Certificate name"
    description: "The name of the certificate to use"
    default: "default"
    required: true

services:

  # Web Server
  nginx-web:
    scale: 2
    start_on_create: true
   
  # Load balancer
  loadbalancer:
    start_on_create: true
    
    lb_config:

      # Hostname to map
      hostname: ${EXTERNAL_FQDN}
    
      # Available certificates
      certs:
      - ${CERTIFICATE_NAME}
      
      # Default cert
      default_cert: ${CERTIFICATE_NAME}
      
      port_rules:
      
      # HTTPS traffic  
      - priority: 1
        protocol: https
        service: nginx-web
        source_port: 443
        target_port: 80
        
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
