version: '2'

# Catalog
catalog:
  name: "Sample nginx"
  version: "v0.0.1"
  description: "A sample nginx server"
  
  # User questions
  questions:
  
  # Subdomain
  - variable: "SUBDOMAIN"
    type: "string"
    label: "The subdomain to use"
    description: "The subdomain to use. Example nginx."
    default: "nginx"
    required: true
  
  # Subdomain
  - variable: "DOMAIN"
    type: "string"
    label: "The domain to use"
    description: "The domain to use. Example dsu.nestle.biz"
    default: "dsu.nestle.biz"
    required: true
  
  # Name of the certificate to use
  - variable: "CERTIFICATE_NAME"
    type: "string"
    label: "Certificate name"
    description: "The name of the certificate to use"
    default: "default"
    required: true

services:

  # Web Server
  nginx-web:
    scale: 2
    start_on_create: true
   
  # Load balancer
  loadbalancer:
    start_on_create: true
    
    lb_config:

      # Hostname to map
      
    
      # Available certificates
      certs:
      - ${CERTIFICATE_NAME}
      
      # Default cert
      default_cert: ${CERTIFICATE_NAME}
      
      port_rules:
      
      # HTTPS traffic  
      - priority: 1
        hostname: ${SUBDOMAIN}.${DOMAIN}
        protocol: http
        service: nginx-web
        source_port: 8080
        target_port: 80
        
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
