# notemplating
.catalog:
  name: "Azure Zone DNS"
  version: "v0.1.0"
  description: "Rancher External DNS service powered by Azure."
  minimum_rancher_version: v1.6.0-rc1
  questions:
    - variable: "AZURE_RESOURCE_GROUP"
      label: "Azure resource group"
      description: "Azure resource group in which is the zone DNS."
      type: "string"
      required: true
    - variable: "AZURE_CLIENT_ID"
      label: "Azure client ID"
      description: "Azure client ID."
      type: "string"
      required: true
    - variable: "AZURE_CLIENT_SECRET"
      label: "Azure client secret"
      description: "Azure client secret."
      type: "password"
      required: true
    - variable: "AZURE_SUBSCRIPTION_ID"
      label: "Azure subscription ID"
      description: "Azure subscription ID."
      type: "string"
      required: true
    - variable: "AZURE_TENANT_ID"
      label: "Azure tenant ID"
      description: "Azure tenant ID."
      type: "string"
      required: true
    - variable: "ROOT_DOMAIN"
      label: "Root Domain"
      description: "The domain name managed by Azure."
      type: "string"
      required: true
    - variable: "TTL"
      label: "TTL"
      description: "The resource record cache time to live (TTL), in seconds"
      type: "int"
      default: 60
      required: false
    - variable: "NAME_TEMPLATE"
      label: "DNS Name Template"
      description: |
        Name template used to construct the subdomain part (left of the root domain name) of the DNS record names.
        Supported placeholders: %{{service_name}}, %{{stack_name}}, %{{environment_name}}.
        By default DNS entries will be named '<service>.<stack>.<environment>.<domain>'.
      type: "string"
      default: "%{{service_name}}.%{{stack_name}}.%{{environment_name}}"
      required: false

azuredns:
  health_check:
    port: 1000
    interval: 15000
    unhealthy_threshold: 2
    request_line: GET / HTTP/1.0
    healthy_threshold: 2
    response_timeout: 2000