apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: test-namespace
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.images.server.repository }}:{{ .Values.images.server.tag }}"
        imagePullPolicy: {{ .Values.images.server.pullPolicy }}
        ports:
        - containerPort: 8200
          name: source-port
          protocol: TCP
        - containerPort: 8229
          name: dest-port
          protocol: TCP
        env:
          - name: KUBERNETES_DEPLOYED
            value: "{{ now }}"


