apiVersion: v1
kind: Service
metadata:
  name: "pf2"
  labels:
    app: "pf2-application"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: external-port
    port: {{ .Values.service.sourcePort }}
    targetPort: 8200
{{- if hasKey .Values.service "nodePort" }}
    nodePort: {{ .Values.service.nodePort }}
{{- end }}
  - name: internal-port
    port: {{ .Values.service.destPort }}
    targetPort: 8229
{{- if hasKey .Values.service "nodePort" }}
    nodePort: {{ .Values.service.nodePort }}
{{- end }}
  selector:
    app: "pf2"
    release: {{ .Release.Name | quote }}
    component: server
