apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" }}
  labels:
    app: {{ template "name" }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: externalPort
    port: {{ .Values.service.sourcePort }}
    targetPort: 8200
{{- if hasKey .Values.service "nodePort" }}
    nodePort: {{ .Values.service.nodePort }}
{{- end }}
  - name: internalPort
    port: {{ .Values.service.destPort }}
    targetPort: 8229
{{- if hasKey .Values.service "nodePort" }}
    nodePort: {{ .Values.service.nodePort }}
{{- end }}
  selector:
    app: {{ template "pf2.name" . }}
    release: {{ .Release.Name | quote }}
    component: server
